In [1]:
df=pd.read_csv(r"C:\Users\Abdur rahim nishad\Downloads\agora.csv")

<IPython.core.display.Javascript object>

In [2]:
df.head()

Marketing Spend  Administration  Transport     Area     Profit
0        114523.61       136897.80  471784.10    Dhaka  192261.83
1        162597.70       151377.59  443898.53      Ctg  191792.06
2        153441.51       101145.55  407934.54  Rangpur  191050.39
3        144372.41       118671.85  383199.62    Dhaka  182901.99
4        142107.34        91391.77  366168.42  Rangpur  166187.94

In [3]:
df.shape

(50, 5)

In [4]:
pd.set_option("display.max_rows",None)
pd.set_option("display.max_columns",None)

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

In [5]:
df.Transport=df.Transport.fillna(df.Transport.median())

In [6]:
from sklearn.preprocessing import LabelEncoder

In [7]:
le=LabelEncoder()

In [8]:
 df.Area=le.fit_transform(df["Area"])

In [9]:
for column in df.columns:
    if df[column].dtype==np.number:
        continue
    df[column]=le.fit_transform(df[column])

<IPython.core.display.Javascript object>

C:\Users\ABDURR~1\AppData\Local\Temp/ipykernel_2212/1696928730.py:2: DeprecationWarning: Converting `np.inexact` or `np.floating` to a dtype is deprecated. The current result is `float64` which is not strictly correct.
  if df[column].dtype==np.number:


<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

In [10]:
x=df.iloc[:,:-1]

In [11]:
x

Marketing Spend  Administration  Transport  Area
0         114523.61       136897.80  471784.10     1
1         162597.70       151377.59  443898.53     0
2         153441.51       101145.55  407934.54     2
3         144372.41       118671.85  383199.62     1
4         142107.34        91391.77  366168.42     2
5         131876.90        99814.71  362861.36     1
6         134615.46       147198.87  127716.82     0
7         130298.13       145530.06  323876.68     2
8         120542.52       148718.95  311613.29     1
9         123334.88       108679.17  304981.62     0
10        101913.08       110594.11  229160.95     2
11        100671.96        91790.61  249744.55     0
12         93863.75       127320.38  249839.44     2
13         91992.39       135495.07  252664.93     0
14        119943.24       156547.42  256512.92     2
15        165349.20       122616.84  261776.23     1
16         78013.11       121597.55  264346.06     0
17         94657.16       145077.58  282574.31     1
18         91749.16       114175.79  294919.57     2
19         86419.70       153514.11  214634.81     1
20         76253.86       113867.30  298664.47     0
21         78389.47       153773.43  299737.29     1
22         73994.56       122782.75  303319.26     2
23         67532.53       105751.03  304768.73     2
24         77044.01        99281.34  140574.81     1
25         64664.71       139553.16  137962.62     0
26         75328.87       144135.98  134050.07     2
27         72107.60       127864.55  353183.81     1
28         66051.52       182645.56  118148.20     2
29         65605.48       153032.06  107138.38     1
30         61994.48       115641.28   91131.24     2
31         61136.38       152701.92   88218.23     1
32         63408.86       129219.61   46085.25     0
33         55493.95       103057.49  214634.81     2
34         46426.07       157693.92  210797.67     0
35         46014.02        85047.44  205517.64     1
36         28663.76       127056.21  201126.82     2
37         44069.95        51283.14  197029.42     0
38         20229.59        65947.93  185265.10     1
39         38558.51        82982.09  174999.30     0
40         28754.33       118546.05  172795.67     0
41         27892.92        84710.77  164470.71     2
42         23640.93        96189.63  148001.11     0
43         15505.73       127382.30   35534.17     1
44         22177.74       154806.14   28334.72     0
45          1000.23       124153.04    1903.93     1
46          1315.46       115816.21  297114.46     2
47             0.00       135426.92       0.00     0
48           542.05        51743.15       0.00     1
49             0.00       116983.80   45173.06     0

In [12]:
y=df.iloc[:,-1]

In [13]:
from sklearn.model_selection import train_test_split

In [14]:
xtrain,ytrain,xtest,ytrain=train_test_split(x,y,test_size=.3,random_state=50)

# Min max scaler/Normalization

In [15]:
from sklearn.preprocessing import MinMaxScaler

In [16]:
mm=MinMaxScaler()

In [17]:
scale_xtrain=mm.fit_transform(xtrain)

In [18]:
scale_xtrain

array([[0.87313643, 0.51299839, 0.81223513, 0.5       ],
       [0.23319442, 0.24130912, 0.3709309 , 0.        ],
       [1.        , 0.54302973, 0.55486446, 0.5       ],
       [0.16869099, 0.25446874, 0.34861436, 1.        ],
       [0.52264964, 0.77823604, 0.45494286, 0.5       ],
       [0.        , 0.50014806, 0.09574943, 0.        ],
       [0.69261666, 0.65174393, 1.        , 0.5       ],
       [0.74590551, 0.43692884, 0.64644319, 0.        ],
       [0.61635061, 0.45150637, 0.48573267, 1.        ],
       [0.47408436, 0.78021012, 0.63532724, 0.5       ],
       [0.57246821, 0.71401273, 0.59894835, 0.5       ],
       [0.        , 0.64054682, 0.        , 0.        ],
       [0.46116861, 0.47642362, 0.63305328, 0.        ],
       [0.17390063, 0.51204073, 0.36626005, 0.        ],
       [0.13412668, 0.78807166, 0.06005866, 0.        ],
       [0.45557444, 0.70684477, 0.28413435, 1.        ],
       [0.43609283, 0.58297807, 0.74861321, 0.5       ],
       [0.39946683, 1.        ,

In [19]:
#scale_xtest=mm.transform(xtest)


In [26]:
from sklearn.preprocessing import MinMaxScaler
mm=MinMaxScaler()

In [27]:
x=mm.fit_transform(x)

In [28]:
x

array([[0.69261666, 0.65174393, 1.        , 0.5       ],
       [0.98335946, 0.76197173, 0.94089337, 0.        ],
       [0.92798459, 0.37957895, 0.8646636 , 1.        ],
       [0.87313643, 0.51299839, 0.81223513, 0.5       ],
       [0.85943772, 0.30532804, 0.77613557, 1.        ],
       [0.797566  , 0.3694479 , 0.76912588, 0.5       ],
       [0.81412828, 0.73016111, 0.27071031, 0.        ],
       [0.7880179 , 0.71745725, 0.68649342, 1.        ],
       [0.72901786, 0.74173276, 0.66049977, 0.5       ],
       [0.74590551, 0.43692884, 0.64644319, 0.        ],
       [0.61635061, 0.45150637, 0.48573267, 1.        ],
       [0.60884455, 0.30836422, 0.52936195, 0.        ],
       [0.56766982, 0.57883556, 0.52956308, 1.        ],
       [0.55635219, 0.64106561, 0.53555202, 0.        ],
       [0.72539353, 0.8013272 , 0.54370828, 1.        ],
       [1.        , 0.54302973, 0.55486446, 0.5       ],
       [0.47180821, 0.53527036, 0.56031151, 0.        ],
       [0.57246821, 0.71401273,

In [23]:
df_x=pd.DataFrame(x,columns=["Marketing Spend","Administration","Transport","Area"])

<IPython.core.display.Javascript object>

In [24]:
df_x

Marketing Spend  Administration  Transport  Area
0          0.692617        0.651744   1.000000   0.5
1          0.983359        0.761972   0.940893   0.0
2          0.927985        0.379579   0.864664   1.0
3          0.873136        0.512998   0.812235   0.5
4          0.859438        0.305328   0.776136   1.0
5          0.797566        0.369448   0.769126   0.5
6          0.814128        0.730161   0.270710   0.0
7          0.788018        0.717457   0.686493   1.0
8          0.729018        0.741733   0.660500   0.5
9          0.745906        0.436929   0.646443   0.0
10         0.616351        0.451506   0.485733   1.0
11         0.608845        0.308364   0.529362   0.0
12         0.567670        0.578836   0.529563   1.0
13         0.556352        0.641066   0.535552   0.0
14         0.725394        0.801327   0.543708   1.0
15         1.000000        0.543030   0.554864   0.5
16         0.471808        0.535270   0.560312   0.0
17         0.572468        0.714013   0.598948   0.5
18         0.554881        0.478772   0.625116   1.0
19         0.522650        0.778236   0.454943   0.5
20         0.461169        0.476424   0.633053   0.0
21         0.474084        0.780210   0.635327   0.5
22         0.447505        0.544293   0.642920   1.0
23         0.408424        0.414638   0.645992   1.0
24         0.465947        0.365388   0.297964   0.5
25         0.391080        0.671958   0.292427   0.0
26         0.455574        0.706845   0.284134   1.0
27         0.436093        0.582978   0.748613   0.5
28         0.399467        1.000000   0.250429   1.0
29         0.396769        0.774566   0.227092   0.5
30         0.374931        0.489928   0.193163   1.0
31         0.369741        0.772053   0.186989   0.5
32         0.383485        0.593294   0.097683   0.0
33         0.335617        0.394134   0.454943   1.0
34         0.280776        0.810055   0.446810   0.0
35         0.278284        0.257032   0.435618   0.5
36         0.173353        0.576825   0.426311   1.0
37         0.266527        0.000000   0.417626   0.0
38         0.122345        0.111636   0.392690   0.5
39         0.233194        0.241309   0.370931   0.0
40         0.173901        0.512041   0.366260   0.0
41         0.168691        0.254469   0.348614   1.0
42         0.142976        0.341852   0.313705   0.0
43         0.093776        0.579307   0.075319   0.5
44         0.134127        0.788072   0.060059   0.0
45         0.006049        0.554724   0.004036   0.5
46         0.007956        0.491260   0.629768   1.0
47         0.000000        0.640547   0.000000   0.0
48         0.003278        0.003502   0.000000   0.5
49         0.000000        0.500148   0.095749   0.0

# standard scaler

In [29]:
from sklearn.preprocessing import StandardScaler

In [30]:
std=StandardScaler()

In [31]:
x=std.fit_transform(x)

In [32]:
x

array([[ 0.89791312,  0.56075291,  2.1873888 ,  0.02462576],
       [ 1.95586034,  1.08280658,  1.94955411, -1.20666232],
       [ 1.75436374, -0.72825703,  1.64281897,  1.25591385],
       [ 1.55478369, -0.09636463,  1.43185602,  0.02462576],
       [ 1.5049372 , -1.07991935,  1.28659774,  1.25591385],
       [ 1.27980001, -0.77623907,  1.25839198,  0.02462576],
       [ 1.34006641,  0.93214721, -0.7471445 , -1.20666232],
       [ 1.24505666,  0.87198001,  0.92589352,  1.25591385],
       [ 1.03036886,  0.9869521 ,  0.82129966,  0.02462576],
       [ 1.09181921, -0.45664025,  0.76473846, -1.20666232],
       [ 0.62039825, -0.38759909,  0.11806761,  1.25591385],
       [ 0.59308542, -1.0655396 ,  0.29362415, -1.20666232],
       [ 0.44325987,  0.21544906,  0.29443346,  1.25591385],
       [ 0.4020776 ,  0.51017895,  0.31853193, -1.20666232],
       [ 1.01718075,  1.26919939,  0.35135125,  1.25591385],
       [ 2.01641149,  0.04586785,  0.39624177,  0.02462576],
       [ 0.0944412 ,  0.

# RobustScaler

In [35]:
from sklearn.preprocessing import RobustScaler
rob=RobustScaler()

# MaxAbsScaler

In [36]:
from sklearn.preprocessing import MaxAbsScaler

rob=MaxAbsScaler()

# Power TRansformation

In [43]:
from sklearn.preprocessing import PowerTransformer

In [44]:
scale=PowerTransformer(method="yeo-johnson")

# manual

In [47]:
df["Marketing Spend"].max()

165349.2

In [48]:
df["Marketing Spend"]=df["Marketing Spend"]/df["Marketing Spend"].max()

In [49]:
df["Marketing Spend"]

0     0.692617
1     0.983359
2     0.927985
3     0.873136
4     0.859438
5     0.797566
6     0.814128
7     0.788018
8     0.729018
9     0.745906
10    0.616351
11    0.608845
12    0.567670
13    0.556352
14    0.725394
15    1.000000
16    0.471808
17    0.572468
18    0.554881
19    0.522650
20    0.461169
21    0.474084
22    0.447505
23    0.408424
24    0.465947
25    0.391080
26    0.455574
27    0.436093
28    0.399467
29    0.396769
30    0.374931
31    0.369741
32    0.383485
33    0.335617
34    0.280776
35    0.278284
36    0.173353
37    0.266527
38    0.122345
39    0.233194
40    0.173901
41    0.168691
42    0.142976
43    0.093776
44    0.134127
45    0.006049
46    0.007956
47    0.000000
48    0.003278
49    0.000000
Name: Marketing Spend, dtype: float64